### ISSUE TITLE
swagger.json is always served (even when it is supposed to be disabled)

### ISSUE THREAD

**Issue by rpcope1** [cope-systems/bottle-swagger#10]
From @ereboschi:
> Looks like 2.0.6 fixes the exception. Much obliged.

> Unfortunately, I just discovered that the SwaggerPlugin(serve_swagger_schema=False) doesn't work if serve_swagger_ui=True... Bottle still serves up /swagger.json (because self.serve_swagger_schema = serve_swagger_schema or serve_swagger_ui)... but I can open a second bug for that.

> Thank you.

The fix should make swagger.json not be served when disabled (and frankly also check to make sure the built-in UI is not served when disabled), and provide some satisfactory tests to verify this behavior.

**Comment by rpcope1** [comment]
So, I sat and thought about this, and I think there might be some nuance here. The reason I didn't initially perceive this behavior to be a bug is because the Swagger UI (so far as I can tell), needs a URL from which to pull a Swagger schema, which I had figured necessitated the serving of the swagger.json file, generated from Bravado.

That said, thinking about it some more, I suppose it's also reasonable to serve the UI, and either figure out if it's possible write the schema somehow into the javascript on the UI page (and it load the definition that way), or to allow the user to pull the schema from some user defined URL, and not serve the swagger.json file. Maybe if the user specifies neither to pull from the swagger.json file, nor some other URL, the UI will be served with no URL for the swagger-ui, and maybe the plugin will do something like emit a warning. I am going to think about this, but I think there's some value here.

**Comment by ereboschi** [comment]
Thanks for looking into this. After making my off-hand comment in the other issue, I realized (as you did) that the UI would need a feature to point to a configurable schema location.

The background as to why I wanted to sere the UI, but not the JSON is that I work on a service that processes requests for our corporate needs and for whitelabelled brands... so the service has two hostnames.

I was hoping to have the service serve up a Swagger UI that points back to the service name the user expects to see. Currently, since the hostnames point to the same server, I'm just putting the whitelabelled name into the Swagger schema.

If your team ends up implementing the ability to have the UI get a Swagger schema from a customizable location, that would be great. If you all don't get around to it, no worries. I'm just happy to be working with a library that actually has support behind it.

Thanks again.

**Comment by rpcope1** [comment]
Understanding now what you need, I think the change is pretty reasonable and not too difficult to make. I'll see if I can't get it done relatively soon. Thank you for your input!

**Comment by rpcope1** [comment]
See PR #11.

**Comment by rpcope1** [comment]
Release version 2.0.7 appears to solve the immediate need from this ticket, and should now be available both on Github and pypi.
